const fs=require('fs');const path=require('path');const crypto=require('crypto');
class Memory{
constructor(){this.file=path.join(process.cwd(),'data','memory.json');if(!fs.existsSync(this.file))fs.mkdirSync(path.dirname(this.file),{recursive:true});if(!fs.existsSync(this.file))fs.writeFileSync(this.file,JSON.stringify({facts:[],threads:{},activeThreadId:null},null,2));const m=this.load();let c=false;if(!Array.isArray(m.facts)){m.facts=[];c=true}if(!m.threads){m.threads={};c=true}m.facts=m.facts.map((f,i)=>({id:f.id||`fact_${i}_${this.generateId()}`,fact:String(f.fact||''),source:f.source||'user',confidence:Number.isFinite(Number(f.confidence))?Number(f.confidence):.7,createdAt:f.createdAt||new Date().toISOString(),updatedAt:f.updatedAt||f.createdAt||new Date().toISOString(),tags:Array.isArray(f.tags)?f.tags.slice(0,20):[]}));if(Array.isArray(m.conversations)){const id=this.generateId();m.threads[id]={id,type:'chat',title:'Chat',createdAt:new Date().toISOString(),messages:m.conversations};m.activeThreadId=id;delete m.conversations;c=true}if(!m.activeThreadId||!m.threads[m.activeThreadId]){const ids=Object.keys(m.threads);if(!ids.length){const id=this.generateId();m.threads[id]={id,type:'chat',title:'Chat',createdAt:new Date().toISOString(),messages:[]};m.activeThreadId=id}else m.activeThreadId=ids[0];c=true}if(c)this.save(m)}
generateId(){return crypto.randomBytes(6).toString('hex')}load(){return JSON.parse(fs.readFileSync(this.file,'utf8'))}save(m){fs.writeFileSync(this.file,JSON.stringify(m,null,2))}
rememberFact(fact,meta={}){const m=this.load(),text=String(fact||'').trim();if(!text)throw new Error('Memory fact cannot be empty.');const now=new Date().toISOString(),old=m.facts.find(x=>String(x.fact||'').trim().toLowerCase()===text.toLowerCase());if(old){old.updatedAt=now;if(meta.source)old.source=meta.source;if(Number.isFinite(Number(meta.confidence)))old.confidence=Number(meta.confidence);if(Array.isArray(meta.tags))old.tags=meta.tags.slice(0,20);this.save(m);return old}const e={id:meta.id||`fact_${this.generateId()}`,fact:text,source:meta.source||'user',confidence:Number.isFinite(Number(meta.confidence))?Number(meta.confidence):.7,createdAt:now,updatedAt:now,tags:Array.isArray(meta.tags)?meta.tags.slice(0,20):[]};m.facts.push(e);if(m.facts.length>2000)m.facts=m.facts.slice(-2000);this.save(m);return e}
getFacts(){return this.load().facts}listThreads(){return Object.values(this.load().threads).map(t=>({id:t.id,type:t.type,title:t.title,createdAt:t.createdAt,messageCount:t.messages.length}))}getActiveThreadId(){return this.load().activeThreadId}getActiveThread(){const m=this.load();return m.threads[m.activeThreadId]}
findThreadByTitle(q){const t=String(q||'').trim().toLowerCase(),a=Object.values(this.load().threads);return a.find(x=>x.title.toLowerCase()===t)||a.find(x=>x.title.toLowerCase().includes(t)||t.includes(x.title.toLowerCase()))||null}
setActiveThread(id){const m=this.load();if(!m.threads[id])throw new Error(`No thread with id ${id}`);m.activeThreadId=id;this.save(m)}
createThread(type,title){const m=this.load(),id=this.generateId();m.threads[id]={id,type,title,createdAt:new Date().toISOString(),messages:[]};m.activeThreadId=id;this.save(m);return m.threads[id]}
renameThread(id,title){const m=this.load();if(!m.threads[id])throw new Error(`No thread with id ${id}`);m.threads[id].title=title;this.save(m);return m.threads[id]}
deleteThread(id){const m=this.load();if(!m.threads[id])throw new Error(`No thread with id ${id}`);const ids=Object.keys(m.threads).filter(x=>x!==id);if(!ids.length)throw new Error('Cannot delete your only remaining chat or project');delete m.threads[id];if(m.activeThreadId===id)m.activeThreadId=ids[0];this.save(m);return m.threads[m.activeThreadId]}
addMessage(role,text){const m=this.load(),t=m.threads[m.activeThreadId];t.messages.push({role,text,createdAt:new Date().toISOString()});if(t.messages.length>100)t.messages=t.messages.slice(-100);this.save(m)}
getRecentMessages(limit=20){const m=this.load();return m.threads[m.activeThreadId].messages.slice(-Math.max(1,Math.min(100,limit)))}
clearConversation(){const m=this.load();m.threads[m.activeThreadId].messages=[];this.save(m)}getConversationCount(){const m=this.load();return m.threads[m.activeThreadId].messages.length}}
module.exports=Memory;